const COURSE_STATUS = Object.freeze({
    ALL: 'ALL',
    DRAFT: 'DRAFT',
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    PUBLISHED: 'PUBLISHED',
    REJECTED: 'REJECTED',
    ARCHIVED: 'ARCHIVED',
    SUSPENDED: 'SUSPENDED',
    UNDER_REVIEW: 'UNDER_REVIEW',
    EXPIRED: 'EXPIRED',
    UNPUBLISHED: 'UNPUBLISHED',
});


export default COURSE_STATUS;